---
platform: linux

resource_types:
- name: helm
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/concourse-helm-gcp
    tag: v0.2.0

resources:
- name: dev-site
  type: helm
  source:
    release: dev-site
    cluster_url: https://kubernetes
    cluster_ca: {{cluster_ca}}
    token: {{token}}
    repos:
    - name: gcs-repo
      url: gs://vic-goog-helm-repo

- name: source
  type: git
  source:
    uri: https://github.com/viglesiasce/concourse-continuous-delivery.git
    branch: master
    tag_filter: v*

jobs:
  - name: deploy-chart
    plan:
      - do:
        - get: source
          trigger: true
        - task: build-chart
          file: source/tasks/prep-chart.yaml
        - put: dev-site
          params:
            chart: gcs-repo/nginx
