 ---
platform: linux

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: dev-site
  type: helm
  source:
    release: dev-site
    cluster_url: https://kubernetes
    cluster_ca: {{cluster_ca}}
    token: {{token}}

- name: source
  type: git
  source:
    uri: https://github.com/viglesiasce/concourse-continuous-delivery.git
    branch: master

jobs:
  - name: deploy-chart
    plan:
      - do:
        - get: source
          trigger: true
        - task: build-chart
          file: source/tasks/prep-chart.yaml
        - put: dev-site
          params:
            chart: helm-repo/nginx-0.1.0.tgz
