---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/helm-helper:v0.1.0

inputs:
- name: source

outputs:
- name: helm-repo

run:
  path: bash
  args:
  - -exc
  - |
    mkdir -p helm-repo
    helm init --client-only
    helm package source/nginx -d helm-repo --version $(cat source/VERSION)
