---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/helm-helper
    tag: v0.2.0

inputs:
- name: source

outputs:
- name: helm-repo

run:
  path: bash
  args:
  - -exc
  - |
    mkdir -p helm-repo
    helm init --client-only
    VERSION=$(cat source/VERSION)
    helm package source/nginx -d helm-repo --version $VERSION
    helm gcs push helm-repo/nginx-$VERSION.tgz gs://vic-goog-helm-repo
    